
@'
name: Deploy
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run build
      - name: Deploy to Linode
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.LINODE_IP }}
          username: deploy
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/deploy/vxneo-hybrid
            git pull origin main
            npm install --production
            npm run build
            pm2 restart vxneo
'@ | Out-File -FilePath .github/workflows/deploy.yml -Encoding utf8
